import fs from 'fs'

import { sampleFiles, baseUrl } from './sampleFiles.mjs'

async function fetchSamples(baseUrl, files) {
  return await Promise.all(
    files.map(async sample => {
      const response = await fetch(baseUrl + sample.file)
      const code = await response.text()

      return {
        name: sample.name,
        code,
      }
    }),
  )
}

const samples = await fetchSamples(baseUrl, sampleFiles)
const objString = JSON.stringify(samples)
const fileString = `
// This file is generated by build-scripts/main.mjs
/* eslint-disable */
export default ${objString};
`

// The file is placed in the src directory to include it in the bundle
fs.mkdirSync('./src/data', { recursive: true })
fs.writeFileSync('./src/data/Samples.js', fileString)
